services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: sposko

