services:
  db:
    container_name: sposko-db
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sposko
  api:
    container_name: sposko-api
    image: api
    ports:
      - "8080:8080"
    build:
      context: api
      dockerfile: ./api/Dockerfile
