// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("trainers")]
	public class Trainer
	{
		[Column("id"           , IsPrimaryKey = true)] public Guid     Id          { get; set; } // uuid
		[Column("date_of_birth"                     )] public DateTime DateOfBirth { get; set; } // date
		[Column("info"                              )] public string?  Info        { get; set; } // text
		[Column("verified"                          )] public bool?    Verified    { get; set; } // boolean

		#region Associations
		/// <summary>
		/// notes_trainer_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Note.TrainerId))]
		public IEnumerable<Note> Notes { get; set; } = null!;

		/// <summary>
		/// sport_groups_trainer_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(SportGroup.TrainerId))]
		public IEnumerable<SportGroup> SportGroups { get; set; } = null!;

		/// <summary>
		/// trainers_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(Id), OtherKey = nameof(User.Id))]
		public User Idfkey { get; set; } = null!;
		#endregion
	}
}
