// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace sposko
{
    [Table("children")]
    public class Child
    {
        [Column("id", IsPrimaryKey = true)] public Guid Id { get; set; } // uuid
        [Column("parent_id")] public Guid ParentId { get; set; } // uuid
        [Column("first_name", CanBeNull = false)] public string FirstName { get; set; } = null!; // character varying(64)
        [Column("last_name", CanBeNull = false)] public string LastName { get; set; } = null!; // character varying(64)
        [Column("date_of_birth")] public DateTime DateOfBirth { get; set; } // date
        [Column("phone_number")] public string? PhoneNumber { get; set; } // character varying(32)
        [Column("email")] public string? Email { get; set; } // character varying(64)

        #region Associations
        /// <summary>
        /// child_group_child_id_fkey backreference
        /// </summary>
        [Association(ThisKey = nameof(Id), OtherKey = nameof(ChildGroup.ChildId))]
        public IEnumerable<ChildGroup> ChildGroups { get; set; } = null!;

        /// <summary>
        /// children_parent_id_fkey
        /// </summary>
        [Association(CanBeNull = false, ThisKey = nameof(ParentId), OtherKey = nameof(sposko.Parent.Id))]
        public Parent Parent { get; set; } = null!;

        /// <summary>
        /// notes_child_id_fkey backreference
        /// </summary>
        [Association(ThisKey = nameof(Id), OtherKey = nameof(Note.ChildId))]
        public IEnumerable<Note> Notes { get; set; } = null!;
        #endregion
    }
}
