// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace sposko
{
    [Table("notes")]
    public class Note
    {
        [Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int Id { get; set; } // integer
        [Column("trainer_id")] public Guid TrainerId { get; set; } // uuid
        [Column("child_id")] public Guid ChildId { get; set; } // uuid
        [Column("text")] public string? Text { get; set; } // text
        [Column("crated_time")] public DateTimeOffset? CratedTime { get; set; } // timestamp (6) with time zone

        #region Associations
        /// <summary>
        /// notes_child_id_fkey
        /// </summary>
        [Association(CanBeNull = false, ThisKey = nameof(ChildId), OtherKey = nameof(sposko.Child.Id))]
        public Child Child { get; set; } = null!;

        /// <summary>
        /// notes_trainer_id_fkey
        /// </summary>
        [Association(CanBeNull = false, ThisKey = nameof(TrainerId), OtherKey = nameof(sposko.Trainer.Id))]
        public Trainer Trainer { get; set; } = null!;
        #endregion
    }
}
