// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace sposko
{
    [Table("parents")]
    public class Parent
    {
        [Column("id", IsPrimaryKey = true)] public Guid Id { get; set; } // uuid
        [Column("amount_owed")] public decimal? AmountOwed { get; set; } // numeric(10,5)

        #region Associations
        /// <summary>
        /// children_parent_id_fkey backreference
        /// </summary>
        [Association(ThisKey = nameof(Id), OtherKey = nameof(Child.ParentId))]
        public IEnumerable<Child> Children { get; set; } = null!;

        /// <summary>
        /// parents_id_fkey
        /// </summary>
        [Association(CanBeNull = false, ThisKey = nameof(Id), OtherKey = nameof(User.Id))]
        public User Idfkey { get; set; } = null!;
        #endregion
    }
}
