// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace sposko
{
    [Table("sport_trainings")]
    public class SportTraining
    {
        [Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int Id { get; set; } // integer
        [Column("group_id")] public int GroupId { get; set; } // integer
        [Column("start_date")] public DateTime StartDate { get; set; } // date
        [Column("start_time")] public DateTimeOffset StartTime { get; set; } // time with time zone
        [Column("duration")] public TimeSpan Duration { get; set; } // interval
        [Column("end_date")] public DateTime? EndDate { get; set; } // date
        [Column("repeat_type")] public string? RepeatType { get; set; } // character varying(32)
        [Column("repeat_interval")] public int? RepeatInterval { get; set; } // integer
        [Column("cost")] public decimal Cost { get; set; } // numeric(10,5)

        #region Associations
        /// <summary>
        /// sport_trainings_group_id_fkey
        /// </summary>
        [Association(CanBeNull = false, ThisKey = nameof(GroupId), OtherKey = nameof(SportGroup.Id))]
        public SportGroup Group { get; set; } = null!;

        /// <summary>
        /// training_exceptions_training_id_fkey backreference
        /// </summary>
        [Association(ThisKey = nameof(Id), OtherKey = nameof(TrainingException.TrainingId))]
        public IEnumerable<TrainingException> TrainingExceptions { get; set; } = null!;
        #endregion
    }
}
