// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace sposko
{
    [Table("sport_groups")]
    public class SportGroup
    {
        [Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int Id { get; set; } // integer
        [Column("name", CanBeNull = false)] public string Name { get; set; } = null!; // character varying(64)
        [Column("trainer_id")] public Guid? TrainerId { get; set; } // uuid
        [Column("sport_id")] public int SportId { get; set; } // integer
        [Column("max_members")] public int? MaxMembers { get; set; } // integer
        [Column("min_age")] public int? MinAge { get; set; } // integer
        [Column("max_age")] public int? MaxAge { get; set; } // integer

        #region Associations
        /// <summary>
        /// child_group_group_id_fkey backreference
        /// </summary>
        [Association(ThisKey = nameof(Id), OtherKey = nameof(ChildGroup.GroupId))]
        public IEnumerable<ChildGroup> ChildGroups { get; set; } = null!;

        /// <summary>
        /// sport_groups_sport_id_fkey
        /// </summary>
        [Association(CanBeNull = false, ThisKey = nameof(SportId), OtherKey = nameof(sposko.Sport.Id))]
        public Sport Sport { get; set; } = null!;

        /// <summary>
        /// sport_groups_trainer_id_fkey
        /// </summary>
        [Association(ThisKey = nameof(TrainerId), OtherKey = nameof(sposko.Trainer.Id))]
        public Trainer? Trainer { get; set; }

        /// <summary>
        /// sport_trainings_group_id_fkey backreference
        /// </summary>
        [Association(ThisKey = nameof(Id), OtherKey = nameof(SportTraining.GroupId))]
        public IEnumerable<SportTraining> SportTrainings { get; set; } = null!;
        #endregion
    }
}
