// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("child_group")]
	public class ChildGroup
	{
		[Column("child_id", IsPrimaryKey = true, PrimaryKeyOrder = 0)] public Guid ChildId { get; set; } // uuid
		[Column("group_id", IsPrimaryKey = true, PrimaryKeyOrder = 1)] public int  GroupId { get; set; } // integer

		#region Associations
		/// <summary>
		/// child_group_child_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(ChildId), OtherKey = nameof(Child.Id))]
		public Child Childgroupchildidfkey { get; set; } = null!;

		/// <summary>
		/// child_group_group_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(GroupId), OtherKey = nameof(SportGroup.Id))]
		public SportGroup Childgroupgroupidfkey { get; set; } = null!;
		#endregion
	}
}
